# Generated by Django 3.2 on 2021-05-07 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210505_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='Null', upload_to='images/featured/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
